site_name: pyciv7
theme:
  name: material
  features:
    - content.code.copy
plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
    - docs/gen_about.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    handlers:
      python:
        paths: [src]
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
site_url: !ENV READTHEDOCS_CANONICAL_URL